backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "assets/blog"
    create: true
    delete: true
    identifier_field: "title"
    slug: "{{filename}}"
    sortable_fields: ["date", "title", "language"]
    view_filters:
      - label: Language
        field: language
        pattern: 'en'
      - label: Language
        field: language
        pattern: 'ar'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true}
      - {label: "Language", name: "language", widget: "select", options: [{label: "English", value: "en"}, {label: "Arabic", value: "ar"}], default: "en", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required: false, allow_multiple: false, choose_url: false, media_library: { config: { max_file_size: 2000000 } }}
      - {label: "Categories", name: "categories", widget: "list", field: {label: "Category Name", name: "category_name", widget: "string"}, required: true, hint: "Enter up to 3 categories (e.g., Engineering, 3D Scanning)"}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false, hint: "A short summary for blog listing (max 150 characters)"}
      - {label: "Body", name: "body", widget: "markdown", required: true}

  - name: "translations"
    label: "Website Translations"
    description: "Manage all interface texts for English and Arabic."
    files:
      - file: "data/translations-en.json"
        label: "English Interface Texts"
        name: "en_translations"
        fields:
          - label: "English Texts"
            name: "translations"
            widget: "object"
            fields:
              # ... (all translation fields as in your new config)
      - file: "data/translations-ar.json"
        label: "Arabic Interface Texts"
        name: "ar_translations"
        fields:
          - label: "Arabic Texts"
            name: "translations"
            widget: "object"
            fields:
              # ... (all translation fields as in your new config)

  - name: "site_settings"
    label: "Site Settings"
    description: "Global website configuration and feature toggles."
    file: "data/site-settings.json"
    fields:
      - label: "Sections Visibility"
        name: "sections"
        widget: "object"
        fields:
          - {label: "Show Projects Section", name: "show_projects", widget: "boolean", default: true, hint: "Toggle visibility of the 'Featured Projects' section on the homepage."}
          - {label: "Show Testimonials Section", name: "show_testimonials", widget: "boolean", default: true, hint: "Toggle visibility of the 'What Our Clients Say' section."}
          - {label: "Show Clients Marquee", name: "show_clients", widget: "boolean", default: false, hint: "Toggle visibility of the scrolling client logos."}
          - {label: "Show Map Section", name: "show_map", widget: "boolean", default: true, hint: "Toggle visibility of the embedded map on the contact page."}
      - label: "Company Information"
        name: "site_info"
        widget: "object"
        fields:
          - {label: "Company Name", name: "company_name", widget: "string", required: true}
          - {label: "Contact Email", name: "contact_email", widget: "string", pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$", pattern_human_readable: "Must be a valid email address", required: true}
          - {label: "Contact Phone Number", name: "contact_phone", widget: "string", required: true}

  - name: "blog-categories"
    label: "Blog Categories"
    files:
      - file: "data/blog-categories.json"
        label: "Blog Category Tags"
        name: "categories"
        fields:
          - label: "Available Categories"
            name: "categories"
            widget: "list"
            fields:
              - label: "Category Name"
                name: "name"
                widget: "string"
                hint: "Enter category name in the appropriate language"
              - label: "Category Slug"
                name: "slug"
                widget: "string"
                hint: "URL-friendly version (e.g., 3d-scanning, reverse-engineering)"
              - label: "Language"
                name: "language"
                widget: "select"
                options: ["en", "ar"]
                hint: "Which language this category belongs to"
              - label: "Active"
                name: "active"
                widget: "boolean"
                default: true
              - label: "Color"
                name: "color"
                widget: "color"
                default: "#3b82f6"
              - label: "Order"
                name: "order"
                widget: "number"
                default: 1
                hint: "Display order (0 for 'All' button)"
