backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "assets/blog"
    create: true
    delete: true
    identifier_field: "title"
    slug: "{{filename}}"
    sortable_fields: ["date", "title", "language"]
    view_filters:
      - label: Language
        field: language
        pattern: 'en'
      - label: Language
        field: language
        pattern: 'ar'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true}
      - {label: "Language", name: "language", widget: "select", options: [{label: "English", value: "en"}, {label: "Arabic", value: "ar"}], default: "en", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required: false, allow_multiple: false, choose_url: false, media_library: { config: { max_file_size: 2000000 } }}
      - {label: "Categories", name: "categories", widget: "list", field: {label: "Category Name", name: "category_name", widget: "string"}, required: true, hint: "Enter up to 3 categories (e.g., Engineering, 3D Scanning)"}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false, hint: "A short summary for blog listing (max 150 characters)"}
      - {label: "Body", name: "body", widget: "markdown", required: true}

  - name: "translations"
    label: "Website Translations"
    description: "Manage all interface texts for English and Arabic."
    files:
      - file: "data/translations-en.json"
        label: "English Interface Texts"
        name: "en_translations"
        fields:
          - label: "English Texts"
            name: "translations"
            widget: "object"
            fields:
              - { label: "Nav About", name: "nav_about", widget: "string" }
              - { label: "Nav Services", name: "nav_services", widget: "string" }
              - { label: "Nav Projects", name: "nav_projects", widget: "string" }
              - { label: "Nav Team", name: "nav_team", widget: "string" }
              - { label: "Nav Blog", name: "nav_blog", widget: "string" }
              - { label: "Nav Contact", name: "nav_contact", widget: "string" }
              - { label: "Lang Toggle Arabic Text", name: "lang_toggle_ar_text", widget: "string" }
              - { label: "Lang Toggle English Text", name: "lang_toggle_en_text", widget: "string" }
              - { label: "Blog Results No Posts", name: "blog_results_no_posts", widget: "string" }
              - { label: "Blog Results Showing All", name: "blog_results_showing_all", widget: "string" }
              - { label: "Blog Results Showing Filtered", name: "blog_results_showing_filtered", widget: "string" }
              - { label: "No Results Title", name: "no_results_title", widget: "string" }
              - { label: "No Results Subtitle", name: "no_results_subtitle", widget: "string" }
              - { label: "Team Subtitle", name: "team_subtitle", widget: "string" }
              - { label: "Team Title", name: "team_title", widget: "string" }
              - { label: "Team Description", name: "team_description", widget: "string" }
              - { label: "Team Member 1", name: "team_member1", widget: "string" }
              - { label: "Team Member 1 Role", name: "team_member1_role", widget: "string" }
              - { label: "Team Member 1 Bio", name: "team_member1_bio", widget: "string" }
              - { label: "Team Member 2", name: "team_member2", widget: "string" }
              - { label: "Team Member 2 Role", name: "team_member2_role", widget: "string" }
              - { label: "Team Member 2 Bio", name: "team_member2_bio", widget: "string" }
              - { label: "About Subtitle", name: "about_subtitle", widget: "string" }
              - { label: "About Title", name: "about_title", widget: "string" }
              - { label: "About Description", name: "about_description", widget: "text" }
              - { label: "Years Experience", name: "years_experience", widget: "string" }
              - { label: "Client Satisfaction", name: "client_satisfaction", widget: "string" }
              - { label: "Projects Completed", name: "projects_completed", widget: "string" }
              - { label: "Breadcrumb Blog", name: "breadcrumb_blog", widget: "string" }
              - { label: "Blog Read More", name: "blog_read_more", widget: "string" }
              - { label: "Blog Post Error Title", name: "blog_post_error_title", widget: "string" }
              - { label: "Blog Post Error Subtitle", name: "blog_post_error_subtitle", widget: "string" }
              - { label: "Blog Post Back To Blog", name: "blog_post_back_to_blog", widget: "string" }
              - { label: "Blog Post Share", name: "blog_post_share", widget: "string" }
              - { label: "Blog Post Share Twitter", name: "blog_post_share_twitter", widget: "string" }
              - { label: "Blog Post Share LinkedIn", name: "blog_post_share_linkedin", widget: "string" }
              - { label: "Blog Post Share Copy", name: "blog_post_share_copy", widget: "string" }
              - { label: "Blog Post Copy Success", name: "blog_post_copy_success", widget: "string" }
      - file: "data/translations-ar.json"
        label: "Arabic Interface Texts"
        name: "ar_translations"
        fields:
          - label: "Arabic Texts"
            name: "translations"
            widget: "object"
            fields:
              - { label: "عن", name: "nav_about", widget: "string" }
              - { label: "الخدمات", name: "nav_services", widget: "string" }
              - { label: "المشاريع", name: "nav_projects", widget: "string" }
              - { label: "الفريق", name: "nav_team", widget: "string" }
              - { label: "المدونة", name: "nav_blog", widget: "string" }
              - { label: "اتصل بنا", name: "nav_contact", widget: "string" }
              - { label: "نص زر تبديل اللغة للعربية", name: "lang_toggle_ar_text", widget: "string" }
              - { label: "نص زر تبديل اللغة للإنجليزية", name: "lang_toggle_en_text", widget: "string" }
              - { label: "نتائج المدونة لا يوجد منشورات", name: "blog_results_no_posts", widget: "string" }
              - { label: "نتائج المدونة إظهار الكل", name: "blog_results_showing_all", widget: "string" }
              - { label: "نتائج المدونة إظهار المفلت", name: "blog_results_showing_filtered", widget: "string" }
              - { label: "عنوان لا توجد نتائج", name: "no_results_title", widget: "string" }
              - { label: "عنوان فرعي لا توجد نتائج", name: "no_results_subtitle", widget: "string" }
              - { label: "العنوان الفرعي للفريق", name: "team_subtitle", widget: "string" }
              - { label: "عنوان الفريق", name: "team_title", widget: "string" }
              - { label: "وصف الفريق", name: "team_description", widget: "string" }
              - { label: "عضو الفريق 1", name: "team_member1", widget: "string" }
              - { label: "دور عضو الفريق 1", name: "team_member1_role", widget: "string" }
              - { label: "نبذة عضو الفريق 1", name: "team_member1_bio", widget: "string" }
              - { label: "عضو الفريق 2", name: "team_member2", widget: "string" }
              - { label: "دور عضو الفريق 2", name: "team_member2_role", widget: "string" }
              - { label: "نبذة عضو الفريق 2", name: "team_member2_bio", widget: "string" }
              - { label: "العنوان الفرعي من نحن", name: "about_subtitle", widget: "string" }
              - { label: "عنوان من نحن", name: "about_title", widget: "string" }
              - { label: "وصف من نحن", name: "about_description", widget: "text" }
              - { label: "سنوات الخبرة", name: "years_experience", widget: "string" }
              - { label: "رضا العملاء", name: "client_satisfaction", widget: "string" }
              - { label: "المشاريع المنجزة", name: "projects_completed", widget: "string" }
              - { label: "شريط التنقل المدونة", name: "breadcrumb_blog", widget: "string" }
              - { label: "اقرأ المزيد في المدونة", name: "blog_read_more", widget: "string" }
              - { label: "عنوان خطأ منشور المدونة", name: "blog_post_error_title", widget: "string" }
              - { label: "عنوان فرعي خطأ منشور المدونة", name: "blog_post_error_subtitle", widget: "string" }
              - { label: "زر العودة للمدونة", name: "blog_post_back_to_blog", widget: "string" }
              - { label: "مشاركة منشور المدونة", name: "blog_post_share", widget: "string" }
              - { label: "مشاركة على تويتر", name: "blog_post_share_twitter", widget: "string" }
              - { label: "مشاركة على لينكدإن", name: "blog_post_share_linkedin", widget: "string" }
              - { label: "مشاركة الرابط", name: "blog_post_share_copy", widget: "string" }
              - { label: "تم نسخ رابط المنشور", name: "blog_post_copy_success", widget: "string" }

  - name: "site_settings"
    label: "Site Settings"
    description: "Global website configuration and feature toggles."
    files:
      - file: "data/site-settings.json"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - label: "Sections Visibility"
            name: "sections"
            widget: "object"
            fields:
              - {label: "Show Projects Section", name: "show_projects", widget: "boolean", default: true, hint: "Toggle visibility of the 'Featured Projects' section on the homepage."}
              - {label: "Show Testimonials Section", name: "show_testimonials", widget: "boolean", default: true, hint: "Toggle visibility of the 'What Our Clients Say' section."}
              - {label: "Show Clients Marquee", name: "show_clients", widget: "boolean", default: false, hint: "Toggle visibility of the scrolling client logos."}
              - {label: "Show Map Section", name: "show_map", widget: "boolean", default: true, hint: "Toggle visibility of the embedded map on the contact page."}
          - label: "Company Information"
            name: "site_info"
            widget: "object"
            fields:
              - {label: "Company Name", name: "company_name", widget: "string", required: true}
              - label: "Contact Email"
                name: "contact_email"
                widget: "string"
                pattern: ["^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$", "Must be a valid email address"]
                required: true
              - {label: "Contact Phone Number", name: "contact_phone", widget: "string", required: true}

  - name: "blog-categories"
    label: "Blog Categories"
    files:
      - file: "data/blog-categories.json"
        label: "Blog Category Tags"
        name: "categories"
        fields:
          - label: "Available Categories"
            name: "categories"
            widget: "list"
            fields:
              - label: "Category Name"
                name: "name"
                widget: "string"
                hint: "Enter category name in the appropriate language"
              - label: "Category Slug"
                name: "slug"
                widget: "string"
                hint: "URL-friendly version (e.g., 3d-scanning, reverse-engineering)"
              - label: "Language"
                name: "language"
                widget: "select"
                options: ["en", "ar"]
                hint: "Which language this category belongs to"
              - label: "Active"
                name: "active"
                widget: "boolean"
                default: true
              - label: "Color"
                name: "color"
                widget: "color"
                default: "#3b82f6"
              - label: "Order"
                name: "order"
                widget: "number"
                default: 1
                hint: "Display order (0 for 'All' button)"
